version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "4001:4001"

  order-service:
    build: ./order-service
    ports:
      - "4002:4002"

  soporte-service:
    build: ./soporte-service
    ports:
      - "4003:4003"
