apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-admin-hpa
  namespace: mi-aplicacion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-admin
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Autoescalado si el CPU supera el 80%
