apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: sa-p5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        ports:
        - containerPort: 4004
        resources:
          requests:
            cpu: "200m"    # 0.2 CPU
            memory: "256Mi" # 256 MB RAM
          limits:
            cpu: "500m"    # 0.5 CPU
            memory: "512Mi" # 512 MB RAM
